//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int id { get; set; }
        public Nullable<double> rate { get; set; }
        public string noi_dung { get; set; }
        public Nullable<System.DateTime> thoi_gian_dang { get; set; }
        public Nullable<int> khach_hang_id { get; set; }
        public Nullable<int> phim_id { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
