//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_TheLoai
    {
        public int id { get; set; }
        public Nullable<int> phim_id { get; set; }
        public Nullable<int> theloai_id { get; set; }
    
        public virtual Phim Phim { get; set; }
        public virtual TheLoaiPhim TheLoaiPhim { get; set; }
    }
}
