//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GheNgoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GheNgoi()
        {
            this.CT_Orders = new HashSet<CT_Orders>();
        }
    
        public int id { get; set; }
        public string hang { get; set; }
        public Nullable<int> cot { get; set; }
        public Nullable<decimal> gia_ghe { get; set; }
        public Nullable<int> phong_chieu_id { get; set; }
        public Nullable<int> loai_ghe_id { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_Orders> CT_Orders { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
        public virtual LoaiGhe LoaiGhe { get; set; }
    }
}
