//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.CT_DichVu = new HashSet<CT_DichVu>();
            this.CT_Orders = new HashSet<CT_Orders>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<System.DateTime> ngay_mua { get; set; }
        public Nullable<decimal> tong_tien { get; set; }
        public string phuong_thuc_thanh_toan { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> khachhang_id { get; set; }
        public Nullable<int> phim_id { get; set; }
        public Nullable<int> phong_chieu_id { get; set; }
        public Nullable<int> so_luong_ve { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DichVu> CT_DichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_Orders> CT_Orders { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
    }
}
