//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.CT_TheLoai = new HashSet<CT_TheLoai>();
            this.Orders = new HashSet<Order>();
            this.SuatChieux = new HashSet<SuatChieu>();
        }
    
        public int id { get; set; }
        public string ten_phim { get; set; }
        public string noi_dung { get; set; }
        public string trailer { get; set; }
        public string dao_dien { get; set; }
        public string dien_vien { get; set; }
        public string anh { get; set; }
        public Nullable<int> thoi_luong { get; set; }
        public Nullable<System.DateTime> ngay_cong_chieu { get; set; }
        public string NgonNgu { get; set; }
        public string Banner { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> comingsoon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_TheLoai> CT_TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuatChieu> SuatChieux { get; set; }
    }
}
