//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuatChieu_KhungGio
    {
        public int id { get; set; }
        public Nullable<int> khung_gio_id { get; set; }
        public Nullable<int> suat_chieu_id { get; set; }
    
        public virtual KhungGio KhungGio { get; set; }
        public virtual SuatChieu SuatChieu { get; set; }
    }
}
